export const paths = {
  home: "/",
  landing: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  terms: "/termos",
  privacy: "/privacidade",
  characters: "/characters",
  gmArea: "/gm",
  gmWorkspaces: "/gm/workspaces",
  subscription: "/subscription",
  workspace: (workspaceId: string) => `/workspaces/${workspaceId}`,
  campaign: (campaignId: string) => `/campaigns/${campaignId}`,
  character: (characterId: string) => `/characters/${characterId}`,
  publicCharacter: (token: string) => `/c/${token}`,
} as const;
